### ISSUE TITLE
Regions dropdown disappears on mobile

### ISSUE THREAD

**Issue by rali14** [Astoundify/wp-job-manager-regions#35]
The dropdown regions search field on homepage disappears when viewed on mobile. Works as expected on desktop.

Confirmed on test drive.

Relevant ticket: https://secure.helpscout.net/conversation/82661531/19859/

**Comment by rali14** [comment]
Just want to follow up on this ... has this fix been released?

Had another user with the same issue and the old customer is following up on this.

**Comment by spencerfinnell** [comment]
It was fixed in the theme. Which are they reporting?

**Comment by rali14** [comment]
Hm, still doesn't seem to display for this user: https://secure.helpscout.net/conversation/82661531/19859/

Also, region disappears on testdrive when viewed on mobile: https://testdrive.astoundify.com/jobify/

**Comment by spencerfinnell** [comment]
This is due to CSS in Jobify.
