### ISSUE TITLE
Bug in Regions dropdown

### ISSUE THREAD

**Issue by Gachari** [Astoundify/wp-job-manager-regions#69]
Overview:
The regions dropdown isn't rendered and instead the location field is rendered despite having listings associated to the regions. There seems to be a JS error generated:
Uncaught ReferenceError: job_manager_select2_multiselect_args is not defined
   at Object.addSubmission (main.js?ver=20140525:33)
   at HTMLDocument.<anonymous> (main.js?ver=20140525:20)
   at HTMLDocument.dispatch (jquery.js?ver=1.12.4:3)
   at HTMLDocument.r.handle (jquery.js?ver=1.12.4:3)
   at Object.trigger (jquery.js?ver=1.12.4:3)
   at Object.a.event.trigger (jquery-migrate.min.js?ver=1.4.1:2)
   at a.fn.init.triggerHandler (jquery.js?ver=1.12.4:3)
   at Function.ready (jquery.js?ver=1.12.4:2)
   at HTMLDocument.K (jquery.js?ver=1.12.4:2)

Expected Result: 
Once filter by region is enabled, listing regions assigned to listings and the filter added amongst the search filters, the Regions dropdown should be displayed.

Actual Result:
Regions dropdown is not rendered. Instead, the location field is rendered.

Plugin version: 
1.16.0

**Comment by adampickering** [comment]
Hey @spencerfinnell can you have a look at this issue, Sample ticket: https://secure.helpscout.net/conversation/756459888/160216/

**Comment by spencerfinnell** [comment]
Try these:

WPJM 1.32.0 beta https://github.com/Automattic/WP-Job-Manager/releases/download/1.32.0-beta2/wp-job-manager-1.32.0-beta2.zip

Regions beta https://github.com/Astoundify/wp-job-manager-regions/archive/master.zip

**Comment by Dubaidogfish** [comment]
This error is popping up for a lot of people. I only noticed the dropdown not working today when checked the box in job listing settings for search by region but had seen that console error recently and found this: 
https://wordpress.org/support/topic/job_manager_select2_multiselect_args-is-not-defined/

Seems this Chosen.JS to Select2 change in WPJM is causing issues for lots of related plugins explained quite well at base of this post relating to WP Job Manager Field Editor too which awaits a fix too:

https://plugins.smyl.es/blog/wp-job-manager-1-32-0-warning-how-to-downgrade

**Comment by Dubaidogfish** [comment]
There is syntax error in chrome console in wp-job-manager-locations/assets/main/js line 33 for an unexpected )

`if ( typeof job_manager_select2_args !== 'undefined' ) ) {`

This creates a few issues down the file. Removing it seems to solve the problem without any side effects, the same problem repeats lower down on line 75.

Once this is fixed the drop down search by location then works n the job search panel.

**Comment by spencerfinnell** [comment]
1.17.1 should fix that syntax error. 

https://github.com/Astoundify/wp-job-manager-regions/commit/2765b0b5b44bca50571bb3cc1d3dfa55331c47d3

Install that version from Github and clear your cache. An official version will be released tomorrow.

**Comment by adampickering** [comment]
It’s already been uploaded to WordPress.org the 1.17.1 version

**Comment by Dubaidogfish** [comment]
Thanks, it's mostly working now on 1.17.2. However on the Resumes search page where this same main.js file that you modified is used, I'm still getting an error in the chrome console, whether the search by region checkbox in resume settings is selected or not (region drop down doesn't appear and there's no text next to the pin icon on the found resumes):

 main.js?ver=20140525:13 Uncaught ReferenceError: job_manager_select2_args is not defined
    at Object.init (main.js?ver=20140525:13)
    at main.js?ver=20140525:106
    at main.js?ver=20140525:108
init @ main.js?ver=20140525:13
(anonymous) @ main.js?ver=20140525:106
(anonymous) @ main.js?ver=20140525:108

This is putting a red cross at the new line 13:
`this.select2_args = job_manager_select2_args || {};`

The job search has no issue with that line 13 though which now works fine with region search and opening the single job. Opening single resume gives above error again as well as resume search page.

**Comment by spencerfinnell** [comment]
Can you please try this version: https://github.com/Astoundify/wp-job-manager-regions/archive/master.zip

**Comment by Dubaidogfish** [comment]
Thanks for the quick reply, the error has gone from the console using that but the search by region drop down is not appearing for resumes nor region on pin icon, still all working for jobs. Have cleared browser cache and done ctrl f5 page loads.

**Comment by spencerfinnell** [comment]
@Dubaidogfish Region support for Resumes was never implemented. #55 

What are you referring to with "region on pin icon"

**Comment by Dubaidogfish** [comment]
Ah ok. Just in Resumes>Settings>Resume Listings there is: 

**Filter Location Display** [checkbox] Display Region
(_Replace the entered address with the selected region on output_)

**Search by Region** [checkbox] Search by Region
(_Use a dropdown of defined regions instead of a text input. Disables radius search._)

In terms of location next to pin icon I mean class 'icon-location' in the search results table 
div.job_listing-location.job_listing__column contains a.google_map_link which relates to the predefined selected region for the job and prints the place name in text next to the icon. This also shows in the single job listing page job-listing-meta.meta where li.location names the region in text as a.google_map_link. This all works well on jobs.

On Resumes search table results div.resume-location.resume__column equivalent to the above it only shows the location icon in the ::before, no place name like it does for jobs. This is also true opening the single resume page in the top meta data for li.location it only shows the i.icon-location.

Searching the location field on the resume page does bring up the correct resume(s) for that location (you can only check this by going to edit the resume on back end and reading the 'Candidate Location' field as it isn't shown anywhere on front side. Trying to input associated region in the location search field draws a blank but this is where the region dropdown search would be expected to work. 

The 'All Resumes' location column in the admin dashboard is also empty yet shows place names correctly for the 'All Jobs' section.

When submitting a new resume, Region is a compulsory field by default, so seems strange to have it required yet not work with it.  https://wordpress.org/support/topic/region-is-required-resume-creations-page/

Finally in the Resumes wp admin Dashboard there is another uncaught error relating to Stats but it works ok for the Jobs section.

 Uncaught ReferenceError: wpjms is not defined
    at HTMLDocument.<anonymous> (edit.php?post_type=resume:2493)
    at i (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-tou&load[]=ch-punch,iris,wp-color-picker,moxiejs,plupload&ver=5.0.3:2)
    at Object.fireWith [as resolveWith] (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-tou&load[]=ch-punch,iris,wp-color-picker,moxiejs,plupload&ver=5.0.3:2)
    at Function.ready (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-tou&load[]=ch-punch,iris,wp-color-picker,moxiejs,plupload&ver=5.0.3:2)
    at HTMLDocument.K (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-tou&load[]=ch-punch,iris,wp-color-picker,moxiejs,plupload&ver=5.0.3:2)

Thanks.

**Comment by spencerfinnell** [comment]
Thank you for the information. Try this:

https://github.com/Astoundify/wp-job-manager-regions/archive/master.zip

Should fix everything except the location link in the admin column -- unfortunately this cannot be linked to the region taxonomy archive page and it instead uses Google Maps.

An update to Jobify will link the region in the single resume view on the frontend.

FYI the blank locations previously means your locations are not being geocoded: https://jobify.astoundify.com/article/1023-create-a-google-maps-api-key

**Comment by Dubaidogfish** [comment]
Thank you! 

So search by region option is now removed from settings. 

I can now see the previously empty location column populated on wp admin dashboard showing the assigned choice of predefined region (so long as I have Filter Location Display -Display Region checkbox chosen in settings), this links to google maps webpage if clicked, with that region place name used as a search term which is fine and is same on jobs for me. I have not set up the maps api as trying to see what I can do without it due to reading about issues on lookup limits on shared servers and potential charges even when client side geocoding https://wordpress.org/support/plugin/wp-job-manager-client-side-geocoder/ - I have removed any maps from pages in my child theme anyway.

The resume search table now shows the region name next to the pin icon which was missing before, it also shows in the meta data on the single resume page now which didn't before. Clicking on the region link in that resume meta takes you to a post of the main resume content rather than google maps webpage but you say I just need to update the jobify theme to fix that.

The keyword search field will also help filter by region if type one in and the location field still filters by the other 'location' term. So all looks much improved.  Understood about geocoding locations and now realise why they were blank but am preferring the regions option for now. 

Thanks again. 

(I still get the wpjms undefined error in Resumes wp admin section relating to the Astoundify Stats plugin but is not really related to Regions, it's the first 'action' line that gets the error.)

`<script type="text/javascript">
jQuery( document ).ready( function( $ ){
$( '<option>' ).val( 'wpjms_stats' ).text( wpjms.view_stats ).appendTo( "select[name='action']" );
$( '<option>' ).val( 'wpjms_stats' ).text( wpjms.view_stats ).appendTo( "select[name='action2']" );
$( 'a.icon-stats' ).attr( 'target', '_blank' );
});
</script>`
